<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>NetworkDevice.Android</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>SPARC Mobile</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>br.com.sparc.mobile</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>0.8.87</ApplicationDisplayVersion>
		<ApplicationVersion>57</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
		<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
		<AndroidPackageFormats>apk</AndroidPackageFormats>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#0B132B" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#0B132B" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NetworkDevice.Core\NetworkDevice.Core.csproj" />
		<ProjectReference Include="..\NetworkDevice.Protocols\NetworkDevice.Protocols.csproj" />
		<ProjectReference Include="..\NetworkDevice.Cisco\NetworkDevice.Cisco.csproj" />
		<ProjectReference Include="..\NetworkDevice.Fortinet\NetworkDevice.Fortinet.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
		<PackageReference Include="UsbSerialForAndroid.Net" Version="1.0.6" />
	</ItemGroup>


</Project>
